spring:
  application:
    name: batch-service
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
      
server:
  port: 10002
  
---
spring:
  profiles: local
  datasource:
    initialize: true # Will always run data-h2.sql on startup

---
spring:
  profiles: dev
  datasource:
    initialize: false # Will never run data-h2.sql on startup
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  
---
spring:
  profiles: prod

eureka:
  instance:
    prefer-ip-address: true