spring:
  application:
    name: category-service

server:
  port: 10003

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  profiles: dev
  datasource:
    initialize: false # Will never run data-h2.sql on startup
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
  
server:
  port: 80
---
spring:
  profiles: prod

eureka:
  instance:
    prefer-ip-address: true
---
spring:
  profiles: perf
  datasource:
    initialize: false
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 80
