server:
  port: 1234

spring:
  application:
    name: category-service
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
    
eureka:
  client:
    fetch-registry: true
    service-url:
      default: http://localhost:8761/eureka/
