spring:
  application:
    name: location-service

server:
  port: 10004
  
---
spring:
  profiles: local
  datasource:
    initialize: true # Will always run data-h2.sql on startup

---
spring:
  profiles: dev
  datasource:
    initialize: false # Will never run data-h2.sql on startup
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 80
---
spring:
  profiles: prod

eureka:
  instance:
    prefer-ip-address: true