spring:
  application:
    name: quality-audit-service

server:
  port: 10005 
  
---
spring:
  profiles: local
  datasource:
    initialization-mode: always # Will always run data-h2.sql on startup

---
spring:
  profiles: dev
  datasource:
    initialization-mode: never # Will never run data-h2.sql on startup
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  
---
spring:
  profiles: prod

eureka:
  instance:
    prefer-ip-address: true