spring:
  application:
    name: skilltype-service
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
      
server:
  port: 8080
  