spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:caliber;Mode=Oracle
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
      
server:
  port: 10007

---
spring:
  profiles: prod

eureka:
  instance:
    prefer-ip-address: true